## numpy.array()

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


## numpy.zeros()

In [2]:

arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


## numpy.ones()

In [3]:
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


## numpy.arange()

In [4]:
arr = np.arange(0, 10, 2)
print(arr)
type(arr)

[0 2 4 6 8]


numpy.ndarray

## numpy.linspace()

In [5]:
arr = np.linspace(0, 10, 5)
print(arr)
type(arr)

[ 0.   2.5  5.   7.5 10. ]


numpy.ndarray

## numpy.reshape()

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


## numpy.flatten()

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened = arr.flatten()
print(flattened)

[1 2 3 4 5 6]


## numpy.add()

In [8]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 5, 6, 7])
result = np.add(arr1, arr2)
print(result)

[ 5  7  9 11]


## numpy.subtract()

In [9]:
arr1 = np.array([5, 6, 7])
arr2 = np.array([1, 2, 3])
result = np.subtract(arr1, arr2)
print(result)

[4 4 4]


## numpy.multiply()

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.multiply(arr1, arr2)
print(result) 

[ 4 10 18]


## numpy.divide()

In [11]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 5])
result = np.divide(arr1, arr2)
print(result)

[5. 5. 6.]


## numpy.dot()

In [12]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result = np.dot(arr1, arr2)
print(result)

11


## numpy.mean()

In [13]:
arr = np.array([1, 2, 3, 4, 5])
result = np.mean(arr)
print(result) 

3.0


## numpy.median()

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.median(arr)
print(result)

3.5


## numpy.std()

In [15]:
arr = np.array([1, 2, 3, 4, 5])
result = np.std(arr)
print(result)

1.4142135623730951


## numpy.var()

In [16]:
arr = np.array([1, 2, 3, 4, 5])
result = np.var(arr)
print(result) 

2.0


## numpy.max()

In [17]:
arr = np.array([1, 2, 3, 4, 5])
result = np.max(arr)
print(result)

5


## numpy.min()

In [18]:
arr = np.array([1, 2, 3, 4, 5])
result = np.min(arr)
print(result) 

1


## numpy.argsort()

In [19]:
arr = np.array([3, 1, 2, 5, 4])
result = np.argsort(arr)
print(result) 

[1 2 0 4 3]


## numpy.split()

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
result = np.split(arr, 4)
print(result) 

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


## numpy.unique()

In [21]:
arr = np.array([1, 2, 2, 3, 3, 3, 4])
result = np.unique(arr)
print(result) 

[1 2 3 4]
